model:
  name: 'fgnet_2_2_resnet50m_ls_neck_fc_parts'
  load_weights: 'log/fgnet_2_2_resnet50m_ls_neck_fc_parts_market1501_triplet_npairs_separate_nomask_partfeature_1024_avg_240epochs/model.pth.tar-150'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/fgnet_2_2_resnet50m_ls_neck_fc_parts_market1501_triplet_npairs_separate_nomask_partfeature_1024_avg_240epochs/'

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'triplet_npairs_softmax_separate'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
    weight_n: 1.0
    weight_x_parts: 1.0

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 60
  rerank: False
  visactmap: False
  vispartmap: True
  visrank: False
