model:
  name: 'fgnet_2_2_ls_neck'
  load_weights: 'log/fgnet_2_2_ls_neck_market1501_softmax_npairs/model.pth.tar-180'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  save_dir: 'log/fgnet_2_2_ls_neck'

loss:
  name: 'softmax_npairs'
  softmax:
    label_smooth: True

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: True
  eval_freq: 60
  rerank: False
  visactmap: False
  vispartmap: False
  visrank: True

