model:
  name: 'fgnet_1_1_resnet50_fc_parts_bd_tri'
  load_weights: 'log/fgnet_1_1_resnet50_fc_parts_bd_tri_dukemtmcreid_triplet_softmax_dropbatch_topdrop_60/model.pth.tar-330'

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/fgnet_1_1_resnet50_fc_parts_bd_tri_dukemtmcreid_triplet_softmax_dropbatch_topdrop_60'

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 600
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: True
  eval_freq: 60
  rerank: False
  visactmap: False
  visrank: False
  visrankactiv: False
  visrank_topk: 5
  visrankactivthr: False
  maskthr: 0.35

