model:
  name: 'fgnet_1_1_resnet50m_ls_neck_fc_parts_bd'
  load_weights: 'log/fgnet_1_1_resnet50m_ls_neck_fc_parts_bd_market1501_triplet_softmax_partfeature_1024_avg_420/model.pth.tar-390'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/fgnet_1_1_resnet50m_ls_neck_fc_parts_bd_market1501_triplet_softmax_partfeature_1024_avg_420/'

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'triplet_softmax_dropbatch'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
    weight_x_parts: 1.0
  dropbatch:
    weight_db_t: 1.0
    weight_db_x: 1.0


test:
  batch_size: 128
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: True
  eval_freq: 60 
  rerank: False
  visactmap: False
  vispartmap: False
  visrank: False
