model:
  name: 'fgnet_1_1_resnet50_neck_fc_parts_bd_tri'
  pretrained: True

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/fgnet_1_1_resnet50_neck_fc_parts_bd_tri_dukemtmcreid_triplet_softmax_dropbatch_fixbase_10'

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'triplet_softmax_parts_dropbatch'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
    weight_x_parts: 1.0
    weight_t_parts: 1.0
  dropbatch:
    weight_db_t: 1.0
    weight_db_x: 1.0
    top_drop_epoch: -1

train:
  optim: 'adam'
  lr: 1.
  max_epoch: 400
  batch_size: 32
  fixbase_epoch: 10
  open_layers: ['bottleneck_global', 'bottleneck_db', 'reduction_global', 'reduction_db','classifier_global', 'classifier_db', 'batch_drop', 'part_weighters', 'part_feature_generators', 'classifier_parts']
  lr_scheduler: 'warmup_db'
  stepsize: [50, 200, 300]

test:
  batch_size: 32
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 30
  rerank: False
  visactmap: False
