model:
  name: 'fgnet_3_3_resnet50m_ls_neck_fc_parts'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/fgnet_3_3_resnet50m_ls_neck_fc_parts_market1501_triplet_npairs_softmax_csattention
  '

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'triplet_npairs_softmax_csattention'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
    weight_x_parts: 1.0
    weight_n: 1.0

train:
  optim: 'adam'
  lr: 0.0003
  max_epoch: 180
  batch_size: 32
  fixbase_epoch: 10
  open_layers: ['channel_part_attentions', 'spatial_part_attentions', 'part_feature_generators', 'classifier_parts', 'classifier_global', 'fc_fuse', 'bottleneck', 'attention_join', 'spatial_attention_head']
  lr_scheduler: 'multi_step'
  stepsize: [60, 120]

test:
  batch_size: 32
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 60
  rerank: False
  visactmap: False
