model:
  name: 'nodropnet_neck'
  pretrained: True

data:
  type: 'image'
  sources: ['dukemtmcreid']
  targets: ['dukemtmcreid']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/nodropnet_neck_dukemtmcreid_triplet_dropbatch'

cuhk03:
  labeled_images: False

sampler:
  train_sampler: 'RandomIdentitySampler'

loss:
  name: 'triplet_dropbatch'
  softmax:
    label_smooth: True
  triplet:
    weight_t: 1.0
    weight_x: 1.0
  dropbatch:
    weight_db_t: 1.0
    weight_db_x: 1.0

train:
  optim: 'adam'
  lr: 1.
  max_epoch: 400
  batch_size: 64
  fixbase_epoch: 0
  open_layers: ['bottleneck_global', 'bottleneck_db', 'reduction_global', 'reduction_db','classifier_global', 'classifier_db', 'batch_drop', 'bottleneck_drop_bottleneck_features', 'classifier_drop_bottleneck']
  lr_scheduler: 'warmup_db'
  stepsize: [50, 200, 300]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 30
  rerank: True
  visactmap: False
