model:
  name: 'resnet50_bd_neck_botdropfeat_doubot_pose_13_conv_1'
  load_weights: 'log/resnet50_bd_neck_botdropfeat_doubot_pose_13_conv_1_cuhk03_labeled_pose_triplet_dropbatch_dropbotfeatures_topdrop_0/model.pth.tar-400'

data:
  type: 'image'
  sources: ['cuhk03']
  targets: ['cuhk03']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/tmp'

cuhk03:
  labeled_images: True

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 320
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: True
  eval_freq: 60
  rerank: False
  visactmap: False
  visrank: False
  visrankactiv: False
  visrank_topk: 5
  visrankactivthr: False
  maskthr: 0.4