model:
  name: 'resnet50_bd'
  load_weights: 'log/resnet50_bd_market1501_triplet_dropbatch/model.pth.tar-390'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/resnet50_bd_market1501_triplet_dropbatch'

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 32
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: True
  eval_freq: 60
  rerank: False
  visactmap: False
  visrank: False

