model:
  name: 'resnet50_ls'
  load_weights: 'log/resnet50_ls_market1501_softmax_triplet_neck/model.pth.tar-180'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  save_dir: 'log/resnet50_ls_market1501_softmax_triplet_neck'

test:
  batch_size: 128
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 60
  rerank: False
  visactmap: True
  visrank: False

