model:
  name: 'bdnet' #bdnet_neck
  load_weights: 'log/bdnet_neck_doublebot_botstream_market1501_triplet_xent_top_batchdrop_topdrop_0/model.pth.tar-400'

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_crop', 'random_erase']
  save_dir: 'log/bdnet_neck_doublebot_botstream_market1501_triplet_xent_top_batchdrop_topdrop_0'

cuhk03:
  labeled_images: True

sampler:
  train_sampler: 'RandomIdentitySampler'

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: True
  rerank: False
  visactmap: False
  visrank: False
  visrankactiv: False
  visrank_topk: 5
  visrankactivthr: False
  maskthr: 0.5
